package com.ft.backend.work.dao;

import com.ft.backend.work.model.Chedui;

import java.util.List;
import java.util.Map;

public interface CheduiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chedui
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chedui
     *
     * @mbggenerated
     */
    int insert(Chedui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chedui
     *
     * @mbggenerated
     */
    int insertSelective(Chedui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chedui
     *
     * @mbggenerated
     */
    Chedui selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chedui
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Chedui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chedui
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Chedui record);


    int countByCondition(Map<String,Object> params);
    List<Chedui> selectByCondition(Map<String,Object> params);

    Long deleteById(Long id);

    int updateChedui(Chedui chedui);

    List<Chedui> selectByIdList(List<Long> ids);
}