package com.ft.backend.work.dao;

import com.ft.backend.work.client.QueryCondition.ChejianQueryCondition;
import com.ft.backend.work.model.Chejian;

import java.util.List;

public interface ChejianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chejian
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chejian
     *
     * @mbggenerated
     */
    int insert(Chejian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chejian
     *
     * @mbggenerated
     */
    int insertSelective(Chejian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chejian
     *
     * @mbggenerated
     */
    Chejian selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chejian
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Chejian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chejian
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Chejian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chejian
     *
     * @mbggenerated
     */

    Long deleteById(Long id);


    List<Chejian> selectByCondition(ChejianQueryCondition condition);

    int countByCondition(ChejianQueryCondition condition);

    List<Chejian> selectByIdList(List<Long> ids);
}