package com.ft.backend.work.dao;

import com.ft.backend.work.model.FileSet;

public interface FileSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileset
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileset
     *
     * @mbggenerated
     */
    int insert(FileSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileset
     *
     * @mbggenerated
     */
    int insertSelective(FileSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileset
     *
     * @mbggenerated
     */
    FileSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileset
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileSet record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileset
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileSet record);
}