package com.ft.backend.work.dao;


import com.ft.backend.work.client.QueryCondition.GonggaoQueryCondition;
import com.ft.backend.work.model.Gonggao;

import java.util.List;

/**
 * Created by huanghongyi on 2017/10/29.
 */
public interface GonggaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(Gonggao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(Gonggao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    Gonggao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gonggao record);

    List<Gonggao> selectByCondition(GonggaoQueryCondition condition);
    int countByCondition(GonggaoQueryCondition condition);
}
