package com.ft.backend.work.dao;

import com.ft.backend.work.model.Politic;

import java.util.List;
import java.util.Map;

public interface PoliticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politic
     *
     * @mbggenerated
     */
    int insert(Politic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politic
     *
     * @mbggenerated
     */
    int insertSelective(Politic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politic
     *
     * @mbggenerated
     */
    Politic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Politic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Politic record);

    List<Politic> selectByCondition(Map<String,Object> params);

    int countByCondition(Map<String,Object> params);
}