package com.ft.backend.work.dao;

import com.ft.backend.work.model.Politic;
import com.ft.backend.work.model.PositionTitle;

import java.util.List;
import java.util.Map;

public interface PositionTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_title
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_title
     *
     * @mbggenerated
     */
    int insert(PositionTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_title
     *
     * @mbggenerated
     */
    int insertSelective(PositionTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_title
     *
     * @mbggenerated
     */
    PositionTitle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_title
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PositionTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_title
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PositionTitle record);

    List<PositionTitle> selectByCondition(Map<String,Object> params);

    int countByCondition(Map<String,Object> params);
}