package com.ft.backend.work.dao;

import com.ft.backend.work.model.Roleset;

public interface RolesetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleset
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleset
     *
     * @mbggenerated
     */
    int insert(Roleset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleset
     *
     * @mbggenerated
     */
    int insertSelective(Roleset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleset
     *
     * @mbggenerated
     */
    Roleset selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleset
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Roleset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleset
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Roleset record);
}