package com.ft.backend.work.dao;

import com.ft.backend.work.client.vo.TaskScoreVo;
import com.ft.backend.work.client.vo.TaskStasticsVo;
import com.ft.backend.work.model.Chedui;
import com.ft.backend.work.model.Task;

import java.util.List;
import java.util.Map;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    Task selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Task record);

    Long deleteById(Long id);

    int countByCondition(Map<String,Object> params);
    List<Task> selectByCondition(Map<String,Object> params);

    int batchInsert(List<Task> records);
    List<Task> selectByParentIdList(List<Long> ids);
    int deleteByIdList(List<Long> ids);

    List<TaskStasticsVo> selectTaskStasticsList(Map<String,Object> params);
    Integer countTaskStastics(Map<String,Object> params);

    List<TaskScoreVo> selectScoreStasticsList(Map<String,Object> params);
    int countScoreStastics(Map<String,Object> params);


    int countBySubCondition(Map<String,Object> params);
    List<Task> selectBySubCondition(Map<String,Object> params);


    int updateByPrimaryKeySelectiveWithNull(Map<String,Object> params);
}