package com.ft.backend.work.dao;

import com.ft.backend.work.model.Xueli;

import java.util.List;
import java.util.Map;

public interface XueliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueli
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueli
     *
     * @mbggenerated
     */
    int insert(Xueli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueli
     *
     * @mbggenerated
     */
    int insertSelective(Xueli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueli
     *
     * @mbggenerated
     */
    Xueli selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueli
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Xueli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueli
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Xueli record);

    List<Xueli> selectByCondition(Map<String,Object> params);

    int countByCondition(Map<String,Object> params);
}