package com.ft.backend.work.model;

import java.io.Serializable;
import java.util.Date;

public class Chedui implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chedui.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chedui.chedui_name
     *
     * @mbggenerated
     */
    private String cheduiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chedui.chejian_id
     *
     * @mbggenerated
     */
    private Long chejianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chedui.chejian_name
     *
     * @mbggenerated
     */
    private String chejianName;
    private Date createTime;
    private String cheduiInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chedui.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chedui.id
     *
     * @return the value of sys_chedui.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chedui.id
     *
     * @param id the value for sys_chedui.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chedui.chedui_name
     *
     * @return the value of sys_chedui.chedui_name
     *
     * @mbggenerated
     */
    public String getCheduiName() {
        return cheduiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chedui.chedui_name
     *
     * @param cheduiName the value for sys_chedui.chedui_name
     *
     * @mbggenerated
     */
    public void setCheduiName(String cheduiName) {
        this.cheduiName = cheduiName == null ? null : cheduiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chedui.chejian_id
     *
     * @return the value of sys_chedui.chejian_id
     *
     * @mbggenerated
     */
    public Long getChejianId() {
        return chejianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chedui.chejian_id
     *
     * @param chejianId the value for sys_chedui.chejian_id
     *
     * @mbggenerated
     */
    public void setChejianId(Long chejianId) {
        this.chejianId = chejianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chedui.chejian_name
     *
     * @return the value of sys_chedui.chejian_name
     *
     * @mbggenerated
     */
    public String getChejianName() {
        return chejianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chedui.chejian_name
     *
     * @param chejianName the value for sys_chedui.chejian_name
     *
     * @mbggenerated
     */
    public void setChejianName(String chejianName) {
        this.chejianName = chejianName == null ? null : chejianName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chedui.is_deleted
     *
     * @return the value of sys_chedui.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chedui.is_deleted
     *
     * @param isDeleted the value for sys_chedui.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCheduiInfo() {
        return cheduiInfo;
    }

    public void setCheduiInfo(String cheduiInfo) {
        this.cheduiInfo = cheduiInfo;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("Chedui{");
        sb.append("id=").append(id);
        sb.append(", cheduiName='").append(cheduiName).append('\'');
        sb.append(", chejianId=").append(chejianId);
        sb.append(", chejianName='").append(chejianName).append('\'');
        sb.append(", createTime='").append(createTime).append('\'');
        sb.append(", cheduiInfo='").append(cheduiInfo).append('\'');
        sb.append(", isDeleted=").append(isDeleted);
        sb.append('}');
        return sb.toString();
    }
}