package com.ft.backend.work.model;

import java.util.Date;

public class FileSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileset.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileset.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileset.fbr
     *
     * @mbggenerated
     */
    private Integer fbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileset.mstate
     *
     * @mbggenerated
     */
    private Integer mstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileset.id
     *
     * @return the value of fileset.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileset.id
     *
     * @param id the value for fileset.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileset.createtime
     *
     * @return the value of fileset.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileset.createtime
     *
     * @param createtime the value for fileset.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileset.fbr
     *
     * @return the value of fileset.fbr
     *
     * @mbggenerated
     */
    public Integer getFbr() {
        return fbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileset.fbr
     *
     * @param fbr the value for fileset.fbr
     *
     * @mbggenerated
     */
    public void setFbr(Integer fbr) {
        this.fbr = fbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileset.mstate
     *
     * @return the value of fileset.mstate
     *
     * @mbggenerated
     */
    public Integer getMstate() {
        return mstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileset.mstate
     *
     * @param mstate the value for fileset.mstate
     *
     * @mbggenerated
     */
    public void setMstate(Integer mstate) {
        this.mstate = mstate;
    }
}