package com.ft.backend.work.model;

public class Politic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column politic.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column politic.politicname
     *
     * @mbggenerated
     */
    private String politicname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column politic.id
     *
     * @return the value of politic.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column politic.id
     *
     * @param id the value for politic.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column politic.politicname
     *
     * @return the value of politic.politicname
     *
     * @mbggenerated
     */
    public String getPoliticname() {
        return politicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column politic.politicname
     *
     * @param politicname the value for politic.politicname
     *
     * @mbggenerated
     */
    public void setPoliticname(String politicname) {
        this.politicname = politicname == null ? null : politicname.trim();
    }
}