package com.ft.backend.work.model;

import java.util.Date;

public class SysWorker {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.work_number
     *
     * @mbggenerated
     */
    private String workNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.cardid
     *
     * @mbggenerated
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.join_time
     *
     * @mbggenerated
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.zhiwu_id
     *
     * @mbggenerated
     */
    private Integer zhiwuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.zhiwu_jc
     *
     * @mbggenerated
     */
    private String zhiwuJc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.zhiwu_name
     *
     * @mbggenerated
     */
    private String zhiwuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.telno
     *
     * @mbggenerated
     */
    private String telno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.chejian_id
     *
     * @mbggenerated
     */
    private Long chejianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.chejian_name
     *
     * @mbggenerated
     */
    private String chejianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.chedui_id
     *
     * @mbggenerated
     */
    private Long cheduiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.chedui_name
     *
     * @mbggenerated
     */
    private String cheduiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.imgurl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.political_id
     *
     * @mbggenerated
     */
    private Integer politicalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.political
     *
     * @mbggenerated
     */
    private String political;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.work_card_no
     *
     * @mbggenerated
     */
    private String workCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.allow_train_type_id
     *
     * @mbggenerated
     */
    private Integer allowTrainTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.allow_train_type_name
     *
     * @mbggenerated
     */
    private String allowTrainTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.first_get_time
     *
     * @mbggenerated
     */
    private Date firstGetTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.license_img_url
     *
     * @mbggenerated
     */
    private String licenseImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.position_title_id
     *
     * @mbggenerated
     */
    private Integer positionTitleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.position_title
     *
     * @mbggenerated
     */
    private String positionTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.id
     *
     * @return the value of sys_worker.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.id
     *
     * @param id the value for sys_worker.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.work_number
     *
     * @return the value of sys_worker.work_number
     *
     * @mbggenerated
     */
    public String getWorkNumber() {
        return workNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.work_number
     *
     * @param workNumber the value for sys_worker.work_number
     *
     * @mbggenerated
     */
    public void setWorkNumber(String workNumber) {
        this.workNumber = workNumber == null ? null : workNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.name
     *
     * @return the value of sys_worker.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.name
     *
     * @param name the value for sys_worker.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.sex
     *
     * @return the value of sys_worker.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.sex
     *
     * @param sex the value for sys_worker.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.nation
     *
     * @return the value of sys_worker.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.nation
     *
     * @param nation the value for sys_worker.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.cardid
     *
     * @return the value of sys_worker.cardid
     *
     * @mbggenerated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.cardid
     *
     * @param cardid the value for sys_worker.cardid
     *
     * @mbggenerated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.birthday
     *
     * @return the value of sys_worker.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.birthday
     *
     * @param birthday the value for sys_worker.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.join_time
     *
     * @return the value of sys_worker.join_time
     *
     * @mbggenerated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.join_time
     *
     * @param joinTime the value for sys_worker.join_time
     *
     * @mbggenerated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.zhiwu_id
     *
     * @return the value of sys_worker.zhiwu_id
     *
     * @mbggenerated
     */
    public Integer getZhiwuId() {
        return zhiwuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.zhiwu_id
     *
     * @param zhiwuId the value for sys_worker.zhiwu_id
     *
     * @mbggenerated
     */
    public void setZhiwuId(Integer zhiwuId) {
        this.zhiwuId = zhiwuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.zhiwu_jc
     *
     * @return the value of sys_worker.zhiwu_jc
     *
     * @mbggenerated
     */
    public String getZhiwuJc() {
        return zhiwuJc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.zhiwu_jc
     *
     * @param zhiwuJc the value for sys_worker.zhiwu_jc
     *
     * @mbggenerated
     */
    public void setZhiwuJc(String zhiwuJc) {
        this.zhiwuJc = zhiwuJc == null ? null : zhiwuJc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.zhiwu_name
     *
     * @return the value of sys_worker.zhiwu_name
     *
     * @mbggenerated
     */
    public String getZhiwuName() {
        return zhiwuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.zhiwu_name
     *
     * @param zhiwuName the value for sys_worker.zhiwu_name
     *
     * @mbggenerated
     */
    public void setZhiwuName(String zhiwuName) {
        this.zhiwuName = zhiwuName == null ? null : zhiwuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.telno
     *
     * @return the value of sys_worker.telno
     *
     * @mbggenerated
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.telno
     *
     * @param telno the value for sys_worker.telno
     *
     * @mbggenerated
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.chejian_id
     *
     * @return the value of sys_worker.chejian_id
     *
     * @mbggenerated
     */
    public Long getChejianId() {
        return chejianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.chejian_id
     *
     * @param chejianId the value for sys_worker.chejian_id
     *
     * @mbggenerated
     */
    public void setChejianId(Long chejianId) {
        this.chejianId = chejianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.chejian_name
     *
     * @return the value of sys_worker.chejian_name
     *
     * @mbggenerated
     */
    public String getChejianName() {
        return chejianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.chejian_name
     *
     * @param chejianName the value for sys_worker.chejian_name
     *
     * @mbggenerated
     */
    public void setChejianName(String chejianName) {
        this.chejianName = chejianName == null ? null : chejianName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.chedui_id
     *
     * @return the value of sys_worker.chedui_id
     *
     * @mbggenerated
     */
    public Long getCheduiId() {
        return cheduiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.chedui_id
     *
     * @param cheduiId the value for sys_worker.chedui_id
     *
     * @mbggenerated
     */
    public void setCheduiId(Long cheduiId) {
        this.cheduiId = cheduiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.chedui_name
     *
     * @return the value of sys_worker.chedui_name
     *
     * @mbggenerated
     */
    public String getCheduiName() {
        return cheduiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.chedui_name
     *
     * @param cheduiName the value for sys_worker.chedui_name
     *
     * @mbggenerated
     */
    public void setCheduiName(String cheduiName) {
        this.cheduiName = cheduiName == null ? null : cheduiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.imgurl
     *
     * @return the value of sys_worker.imgurl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.imgurl
     *
     * @param imgurl the value for sys_worker.imgurl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.is_deleted
     *
     * @return the value of sys_worker.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.is_deleted
     *
     * @param isDeleted the value for sys_worker.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.political_id
     *
     * @return the value of sys_worker.political_id
     *
     * @mbggenerated
     */
    public Integer getPoliticalId() {
        return politicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.political_id
     *
     * @param politicalId the value for sys_worker.political_id
     *
     * @mbggenerated
     */
    public void setPoliticalId(Integer politicalId) {
        this.politicalId = politicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.political
     *
     * @return the value of sys_worker.political
     *
     * @mbggenerated
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.political
     *
     * @param political the value for sys_worker.political
     *
     * @mbggenerated
     */
    public void setPolitical(String political) {
        this.political = political == null ? null : political.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.work_card_no
     *
     * @return the value of sys_worker.work_card_no
     *
     * @mbggenerated
     */
    public String getWorkCardNo() {
        return workCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.work_card_no
     *
     * @param workCardNo the value for sys_worker.work_card_no
     *
     * @mbggenerated
     */
    public void setWorkCardNo(String workCardNo) {
        this.workCardNo = workCardNo == null ? null : workCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.group_id
     *
     * @return the value of sys_worker.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.group_id
     *
     * @param groupId the value for sys_worker.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.group_name
     *
     * @return the value of sys_worker.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.group_name
     *
     * @param groupName the value for sys_worker.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.allow_train_type_id
     *
     * @return the value of sys_worker.allow_train_type_id
     *
     * @mbggenerated
     */
    public Integer getAllowTrainTypeId() {
        return allowTrainTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.allow_train_type_id
     *
     * @param allowTrainTypeId the value for sys_worker.allow_train_type_id
     *
     * @mbggenerated
     */
    public void setAllowTrainTypeId(Integer allowTrainTypeId) {
        this.allowTrainTypeId = allowTrainTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.allow_train_type_name
     *
     * @return the value of sys_worker.allow_train_type_name
     *
     * @mbggenerated
     */
    public String getAllowTrainTypeName() {
        return allowTrainTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.allow_train_type_name
     *
     * @param allowTrainTypeName the value for sys_worker.allow_train_type_name
     *
     * @mbggenerated
     */
    public void setAllowTrainTypeName(String allowTrainTypeName) {
        this.allowTrainTypeName = allowTrainTypeName == null ? null : allowTrainTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.first_get_time
     *
     * @return the value of sys_worker.first_get_time
     *
     * @mbggenerated
     */
    public Date getFirstGetTime() {
        return firstGetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.first_get_time
     *
     * @param firstGetTime the value for sys_worker.first_get_time
     *
     * @mbggenerated
     */
    public void setFirstGetTime(Date firstGetTime) {
        this.firstGetTime = firstGetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.start_time
     *
     * @return the value of sys_worker.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.start_time
     *
     * @param startTime the value for sys_worker.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.end_time
     *
     * @return the value of sys_worker.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.end_time
     *
     * @param endTime the value for sys_worker.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.address
     *
     * @return the value of sys_worker.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.address
     *
     * @param address the value for sys_worker.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.license_img_url
     *
     * @return the value of sys_worker.license_img_url
     *
     * @mbggenerated
     */
    public String getLicenseImgUrl() {
        return licenseImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.license_img_url
     *
     * @param licenseImgUrl the value for sys_worker.license_img_url
     *
     * @mbggenerated
     */
    public void setLicenseImgUrl(String licenseImgUrl) {
        this.licenseImgUrl = licenseImgUrl == null ? null : licenseImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.position_title_id
     *
     * @return the value of sys_worker.position_title_id
     *
     * @mbggenerated
     */
    public Integer getPositionTitleId() {
        return positionTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.position_title_id
     *
     * @param positionTitleId the value for sys_worker.position_title_id
     *
     * @mbggenerated
     */
    public void setPositionTitleId(Integer positionTitleId) {
        this.positionTitleId = positionTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_worker.position_title
     *
     * @return the value of sys_worker.position_title
     *
     * @mbggenerated
     */
    public String getPositionTitle() {
        return positionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_worker.position_title
     *
     * @param positionTitle the value for sys_worker.position_title
     *
     * @mbggenerated
     */
    public void setPositionTitle(String positionTitle) {
        this.positionTitle = positionTitle == null ? null : positionTitle.trim();
    }
}