package com.ft.backend.work.model;

import java.io.Serializable;
import java.util.Date;

public class Worker implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.work_number
     *
     * @mbggenerated
     */
    private String workNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.cardid
     *
     * @mbggenerated
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.join_time
     *
     * @mbggenerated
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.zhiwu_id
     *
     * @mbggenerated
     */
    private Long zhiwuId;
    private String zhiwuJc;
    private String zhiwuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.telno
     *
     * @mbggenerated
     */
    private String telno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.chejianid
     *
     * @mbggenerated
     */
    private Long chejianId;
    private String chejianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.cheduiid
     *
     * @mbggenerated
     */
    private Long cheduiId;
    private String cheduiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.imgurl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.political_id
     *
     * @mbggenerated
     */
    private Long politicalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.political
     *
     * @mbggenerated
     */
    private String political;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.work_card_no
     *
     * @mbggenerated
     */
    private String workCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.allow_train_type_id
     *
     * @mbggenerated
     */
    private Long allowTrainTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.allow_train_type_name
     *
     * @mbggenerated
     */
    private String allowTrainTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.first_get_time
     *
     * @mbggenerated
     */
    private Date firstGetTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.license_img_url
     *
     * @mbggenerated
     */
    private String licenseImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.position_title_id
     *
     * @mbggenerated
     */
    private Long positionTitleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_worker.position_title
     *
     * @mbggenerated
     */
    private String positionTitle;

    private Long degreeId;
    private String degreeName;

    private String province;

    private String feature;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.id
     *
     * @return the value of worker.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.id
     *
     * @param id the value for worker.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.work_number
     *
     * @return the value of worker.work_number
     *
     * @mbggenerated
     */
    public String getWorkNumber() {
        return workNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.work_number
     *
     * @param workNumber the value for worker.work_number
     *
     * @mbggenerated
     */
    public void setWorkNumber(String workNumber) {
        this.workNumber = workNumber == null ? null : workNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.name
     *
     * @return the value of worker.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.name
     *
     * @param name the value for worker.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.sex
     *
     * @return the value of worker.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.sex
     *
     * @param sex the value for worker.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.nation
     *
     * @return the value of worker.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.nation
     *
     * @param nation the value for worker.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.cardid
     *
     * @return the value of worker.cardid
     *
     * @mbggenerated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.cardid
     *
     * @param cardid the value for worker.cardid
     *
     * @mbggenerated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.birthday
     *
     * @return the value of worker.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.birthday
     *
     * @param birthday the value for worker.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.join_time
     *
     * @return the value of worker.join_time
     *
     * @mbggenerated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.join_time
     *
     * @param joinTime the value for worker.join_time
     *
     * @mbggenerated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.zhiwu_id
     *
     * @return the value of worker.zhiwu_id
     *
     * @mbggenerated
     */
    public Long getZhiwuId() {
        return zhiwuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.zhiwu_id
     *
     * @param zhiwuId the value for worker.zhiwu_id
     *
     * @mbggenerated
     */
    public void setZhiwuId(Long zhiwuId) {
        this.zhiwuId = zhiwuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.telno
     *
     * @return the value of worker.telno
     *
     * @mbggenerated
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.telno
     *
     * @param telno the value for worker.telno
     *
     * @mbggenerated
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.chejianid
     *
     * @return the value of worker.chejianid
     *
     * @mbggenerated
     */
    public Long getChejianId() {
        return chejianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.chejianid
     *
     * @param chejianId the value for worker.chejianid
     *
     * @mbggenerated
     */
    public void setChejianId(Long chejianId) {
        this.chejianId = chejianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.cheduiid
     *
     * @return the value of worker.cheduiid
     *
     * @mbggenerated
     */
        public Long getCheduiId() {
        return cheduiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.cheduiid
     *
     * @param cheduiId the value for worker.cheduiid
     *
     * @mbggenerated
     */
    public void setCheduiId(Long cheduiId) {
        this.cheduiId = cheduiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.is_deleted
     *
     * @return the value of worker.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.is_deleted
     *
     * @param isDeleted the value for worker.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.imgurl
     *
     * @return the value of worker.imgurl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.imgurl
     *
     * @param imgurl the value for worker.imgurl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    public String getZhiwuJc() {
        return zhiwuJc;
    }

    public void setZhiwuJc(String zhiwuJc) {
        this.zhiwuJc = zhiwuJc;
    }

    public String getZhiwuName() {
        return zhiwuName;
    }

    public void setZhiwuName(String zhiwuName) {
        this.zhiwuName = zhiwuName;
    }

    public String getChejianName() {
        return chejianName;
    }

    public void setChejianName(String chejianName) {
        this.chejianName = chejianName;
    }

    public String getCheduiName() {
        return cheduiName;
    }

    public void setCheduiName(String cheduiName) {
        this.cheduiName = cheduiName;
    }

    public Long getPoliticalId() {
        return politicalId;
    }

    public void setPoliticalId(Long politicalId) {
        this.politicalId = politicalId;
    }

    public String getPolitical() {
        return political;
    }

    public void setPolitical(String political) {
        this.political = political;
    }

    public String getWorkCardNo() {
        return workCardNo;
    }

    public void setWorkCardNo(String workCardNo) {
        this.workCardNo = workCardNo;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Long getAllowTrainTypeId() {
        return allowTrainTypeId;
    }

    public void setAllowTrainTypeId(Long allowTrainTypeId) {
        this.allowTrainTypeId = allowTrainTypeId;
    }

    public String getAllowTrainTypeName() {
        return allowTrainTypeName;
    }

    public void setAllowTrainTypeName(String allowTrainTypeName) {
        this.allowTrainTypeName = allowTrainTypeName;
    }

    public Date getFirstGetTime() {
        return firstGetTime;
    }

    public void setFirstGetTime(Date firstGetTime) {
        this.firstGetTime = firstGetTime;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLicenseImgUrl() {
        return licenseImgUrl;
    }

    public void setLicenseImgUrl(String licenseImgUrl) {
        this.licenseImgUrl = licenseImgUrl;
    }

    public Long getPositionTitleId() {
        return positionTitleId;
    }

    public void setPositionTitleId(Long positionTitleId) {
        this.positionTitleId = positionTitleId;
    }

    public String getPositionTitle() {
        return positionTitle;
    }

    public void setPositionTitle(String positionTitle) {
        this.positionTitle = positionTitle;
    }

    public Long getDegreeId() {
        return degreeId;
    }

    public void setDegreeId(Long degreeId) {
        this.degreeId = degreeId;
    }

    public String getDegreeName() {
        return degreeName;
    }

    public void setDegreeName(String degreeName) {
        this.degreeName = degreeName;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getFeature() {
        return feature;
    }

    public void setFeature(String feature) {
        this.feature = feature;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("Worker{");
        sb.append("id=").append(id);
        sb.append(", workNumber='").append(workNumber).append('\'');
        sb.append(", name='").append(name).append('\'');
        sb.append(", sex='").append(sex).append('\'');
        sb.append(", nation='").append(nation).append('\'');
        sb.append(", cardid='").append(cardid).append('\'');
        sb.append(", birthday=").append(birthday);
        sb.append(", joinTime=").append(joinTime);
        sb.append(", zhiwuId=").append(zhiwuId);
        sb.append(", zhiwuJc='").append(zhiwuJc).append('\'');
        sb.append(", zhiwuName='").append(zhiwuName).append('\'');
        sb.append(", telno='").append(telno).append('\'');
        sb.append(", chejianId=").append(chejianId);
        sb.append(", chejianName='").append(chejianName).append('\'');
        sb.append(", cheduiId=").append(cheduiId);
        sb.append(", cheduiName='").append(cheduiName).append('\'');
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", imgurl='").append(imgurl).append('\'');
        sb.append(", politicalId=").append(politicalId);
        sb.append(", political='").append(political).append('\'');
        sb.append(", workCardNo='").append(workCardNo).append('\'');
        sb.append(", groupId=").append(groupId);
        sb.append(", groupName='").append(groupName).append('\'');
        sb.append(", allowTrainTypeId=").append(allowTrainTypeId);
        sb.append(", allowTrainTypeName='").append(allowTrainTypeName).append('\'');
        sb.append(", firstGetTime=").append(firstGetTime);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", address='").append(address).append('\'');
        sb.append(", licenseImgUrl='").append(licenseImgUrl).append('\'');
        sb.append(", positionTitleId=").append(positionTitleId);
        sb.append(", positionTitle='").append(positionTitle).append('\'');
        sb.append(", degreeId=").append(degreeId);
        sb.append(", degreeName='").append(degreeName).append('\'');
        sb.append(", province='").append(province).append('\'');
        sb.append('}');
        return sb.toString();
    }
}