package com.ft.backend.work.model;

public class Xueli {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueli.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueli.degreename
     *
     * @mbggenerated
     */
    private String degreename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueli.id
     *
     * @return the value of xueli.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueli.id
     *
     * @param id the value for xueli.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueli.degreename
     *
     * @return the value of xueli.degreename
     *
     * @mbggenerated
     */
    public String getDegreename() {
        return degreename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueli.degreename
     *
     * @param degreename the value for xueli.degreename
     *
     * @mbggenerated
     */
    public void setDegreename(String degreename) {
        this.degreename = degreename == null ? null : degreename.trim();
    }
}